///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAdd = 'assets/images/add.svg';
  static const String imagesArmchair = 'assets/images/Armchair.svg';
  static const String imagesBackwordArrow = 'assets/images/backwordArrow.svg';
  static const String imagesBasket = 'assets/images/basket.svg';
  static const String imagesBed = 'assets/images/bed.svg';
  static const String imagesBlackLamp = 'assets/images/BlackLamp.png';
  static const String imagesBoarding = 'assets/images/boarding.png';
  static const String imagesChair = 'assets/images/Chair.svg';
  static const String imagesCoffeeChair = 'assets/images/CoffeeChair.png';
  static const String imagesCrown = 'assets/images/crown.svg';
  static const String imagesDesk = 'assets/images/Desk.png';
  static const String imagesDownArrow = 'assets/images/downArrow.svg';
  static const String imagesEye = 'assets/images/eye.svg';
  static const String imagesForwordArrow = 'assets/images/forwordArrow.svg';
  static const String imagesGraphics = 'assets/images/Graphics.svg';
  static const String imagesHome = 'assets/images/home.svg';
  static const String imagesMinimalStand = 'assets/images/MinimalStand.png';
  static const String imagesMinus = 'assets/images/minus.svg';
  static const String imagesNotification = 'assets/images/notification.svg';
  static const String imagesPattern = 'assets/images/pattern.svg';
  static const String imagesPen = 'assets/images/pen.svg';
  static const String imagesPerson = 'assets/images/person.svg';
  static const String imagesSave = 'assets/images/save.svg';
  static const String imagesSearch = 'assets/images/search.svg';
  static const String imagesShoppingBag = 'assets/images/shoppingBag.svg';
  static const String imagesStand = 'assets/images/stand.png';
  static const String imagesStar = 'assets/images/star.svg';
  static const String imagesStarGolden = 'assets/images/starGolden.svg';
  static const String imagesTable = 'assets/images/table.svg';
  static const String imagesWrong = 'assets/images/wrong.svg';

}
